### ISSUE TITLE
Input의 value가 invalid한 값일 때 style 적용

### ISSUE THREAD

**Issue by eotkd4791** [eotkd4791/TIL-archive#24]
input의 value가 invalid한 값일 경우에 invalid라는 가상 클래스(Pseudo class)가 해당 `Input Element`에 적용된다. 따라서 아래의 CSS 코드와 같이 적용하여 form validation에 대한 결과를 사용자에게 제공할 수 있다.

```css
input:invalid {
  border: 3px solid red;
}
```
